# This is a basic workflow to help you get started with Actions

name: Test_Lines

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test_compilation:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./DiscordBotN
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Download jar files
        run: |
          wget -O processing_core.jar "https://github.com/HHSAPCompSci2020/capstone-project-hbb/blob/main/lib/processing_core.jar?raw=true"
          ls
      
      - uses: actions/upload-artifact@master
        with:
          name: jar-artifacts
          path: ./processing_core.jar
      
      - name: Compile the test code
        run: |
          javac -cp .:processing_core.jar LineTest.java
          java Line.java
          
  test_vertical_lines:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: test_compilation
    defaults:
      run:
        working-directory: ./DiscordBotN
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: jar-artifacts
          path: ./DiscordBotN

      - name: Compile the test code
        run: javac -cp .:processing_core.jar LineTest.java
        
      - name: Test vertical lines
        run: java -ea LineTest vertical
          
  test_parallel_lines:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: test_compilation
    defaults:
      run:
        working-directory: ./DiscordBotN
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: jar-artifacts
          path: ./DiscordBotN
          
      - name: Compile the test code
        run: |
          javac -cp .:processing_core.jar LineTest.java
          java Line.java
        
      - name: Test parallel lines
        run: java -ea LineTest parallel
    
  test_intersecting_lines:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: test_compilation
    defaults:
      run:
        working-directory: ./DiscordBotN
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: jar-artifacts
          path: ./DiscordBotN
          
      - name: Compile the test code
        run: |
          javac -cp .:processing_core.jar LineTest.java
          java Line.java
        
      - name: Test intersecting lines
        run: java -ea LineTest intersecting

  test_non_intersecting_lines:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: test_compilation
    defaults:
      run:
        working-directory: ./DiscordBotN
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: jar-artifacts
          path: ./DiscordBotN
          
      - name: Compile the test code
        run: |
          javac -cp .:processing_core.jar LineTest.java
          java Line.java
        
      - name: Test non-intersecting lines
        run: java -ea LineTest non_intersecting
        
  test_collinear_lines:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: test_compilation
    defaults:
      run:
        working-directory: ./DiscordBotN
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: jar-artifacts
          path: ./DiscordBotN
          
      - name: Compile the test code
        run: |
          javac -cp .:processing_core.jar LineTest.java
          java Line.java
        
      - name: Test collinear lines
        run: java -ea LineTest collinear
